version: "3.7"
services:
  front-envoy:
    image: emulator_envoy:latest
    build:
      context: .
      dockerfile: envoy.Dockerfile
    networks:
      - envoymesh
    expose:
      - "8080"
      - "8001"
      - "8443"
    ports:
      - "80:8080"
      - "443:8443"
      - "8001:8001"

  emulator:
    image: emulator_emulator:latest
    build:
      context: ../../src
      dockerfile: Dockerfile
      shm_size: 128M
    networks:
      envoymesh:
        aliases:
          - emulator
    environment:
      - TURN=printf {"iceServers":[{"urls":"turn:global.turn.twilio.com:3478?transport=udp","username":"f795796a4944aea6389d4374a53ec9675609d04d559a612e2eaf0ce9f0f81aed","credential":"R+F0fCGB+YliVSA418nsFfv86GK4cTlbgyD4jobayKg="}]}
    devices: [/dev/kvm]
    shm_size: 128M
    expose:
      - "8554"

  jwt_signer:
    image: emulator_jwt_signer:latest
    build:
      context: ../jwt-provider
      dockerfile: Dockerfile
    networks:
      envoymesh:
        aliases:
          - jwt_signer
    expose:
      - "8080"

  nginx:
    image: emulator_nginx:latest
    build:
      context: ..
      dockerfile: docker/nginx.Dockerfile
    networks:
      envoymesh:
        aliases:
          - nginx
    expose:
      - "80"

networks:
  envoymesh: {}

