version: '3.7'
services:
  front-envoy:
    image: emulator_envoy:latest
    container_name: emulator_envoy
    networks:
      - envoymesh
    expose:
      - '8080'
      - '8001'
      - '8443'
    ports:
      - '80:8080'
      - '443:8443'
      - '8001:8001'

  emulator:
    image: emulator_emulator:latest
    container_name: emulator_emulator
    networks:
      envoymesh:
        aliases:
          - emulator
    environment:
      - TURN=printf {"iceServers":[{"urls":"turn:global.turn.twilio.com:3478?transport=tcp","username":"d984d4740c12c2d6421704ff2c40c0f6652fb11301c3209738cc50afe3c5f530","credential":"j04Gt2+ravkNh9JVzLbbrbjkeDT7e5MBJl1t+s+7Ml8="}]}
    devices: [/dev/kvm]
    gpus: all
    shm_size: 128M
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    expose:
      - '8554'

  jwt_signer:
    image: emulator_jwt_signer:latest
    container_name: emulator_jwt_signer
    networks:
      envoymesh:
        aliases:
          - jwt_signer
    expose:
      - '8080'

  nginx:
    image: emulator_nginx:latest
    container_name: emulator_nginx
    networks:
      envoymesh:
        aliases:
          - nginx
    expose:
      - '80'

networks:
  envoymesh: {}
