version: '3.7'
services:
  front-envoy:
    image: emulator_envoy:latest
    container_name: emulator_envoy
    networks:
      - envoymesh
    expose:
      - '8080'
      - '8001'
      - '8443'
    ports:
      - '80:8080'
      - '8443:8443'
      - '8001:8001'

  emulator:
    image: emulator_emulator:latest
    container_name: emulator_emulator
    runtime: nvidia
    networks:
      envoymesh:
        aliases:
          - emulator
    environment:
      - DISPLAY
      - TURN=printf {"iceServers":[{"urls":"turn:global.turn.twilio.com:3478?transport=tcp","username":"f4fd40dee60cc621d46e90af5475cd9f54913f38b97dccca00bf2dc33a90f1f7","credential":"6wfD8uNqy4F2Gin0oxdLF3Oyno2rIm2QWt7PxtRy9HY="}]}
    devices: [/dev/kvm]
    shm_size: 128M
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    expose:
      - '8554'

  jwt_signer:
    image: emulator_jwt_signer:latest
    container_name: emulator_jwt_signer
    networks:
      envoymesh:
        aliases:
          - jwt_signer
    expose:
      - '8080'

  nginx:
    image: emulator_nginx:latest
    container_name: emulator_nginx
    networks:
      envoymesh:
        aliases:
          - nginx
    expose:
      - '80'

networks:
  envoymesh:
    external:
      name: envoymesh
